services:
  app:
    build: .
    container_name: app_hotel
    working_dir: /var/www
    volumes:
      - ./laravel:/var/www
      - ./php.ini:/usr/local/etc/php/php.ini
    networks:
      - laravel
  webserver:
    image: nginx:latest
    container_name: nginx_server_hotel
    ports:
      - "8100:80"
    volumes:
      - ./laravel:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
  db:
    image: mysql:8.0
    container_name: mysql_db_hotel
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
networks:
  laravel:
    driver: bridge
volumes:
  minio-data:
  mysql_data: